id: P2FAEEEF5
initial_creation_type: ocr
source_metadata:
  volumes:
    dddb5f7558924e78a26bd847a8898f28:
      base_file: v012.txt
      image_group_id: I1PD95857
      title: དཔལ་རྡོ་རྗེ་རྣལ་འབྱོར་མའི་སྒྲུབ་ཐབས།
      total_pages: 1544
      volume_number: 12
